version: '3'
services:
  backend:
    image: libreconsejo-chat
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:80
    container_name: libreconsejo-chat
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'