module.exports = [
    'abuso de drogas',
    'abuso de sustancias',
    'acompañamiento',
    'aflicción',
    'amistad',
    'amor propio',
    'ansia',
    'ansiedad',
    'autoayuda',
    'autoconocimiento',
    'autocuidado',
    'autoestima',
    'autoexigencia',
    'autoexploración',
    'bienestar',
    'bienestar emocional',
    'capacidad de adaptación',
    'cansancio',
    'clínica psicológica',
    'codependencia',
    'comunicación efectiva',
    'confianza en uno mismo',
    'consejería',
    'consuelo',
    'cuidado personal',
    'depresión',
    'desánimo',
    'desarrollo personal',
    'desasosiego',
    'descanso',
    'desesperación',
    'desgaste emocional',
    'desmotivación',
    'desorden alimenticio',
    'desorden emocional',
    'dificultades emocionales',
    'duelo',
    'emociones negativas',
    'emociones positivas',
    'empatía',
    'encierro',
    'energía emocional',
    'entendimiento interpersonal',
    'entrenamiento emocional',
    'equilibrio emocional',
    'esfuerzo personal',
    'estrés',
    'estudios psicológicos',
    'familia',
    'fatiga',
    'felicidad',
    'fortalecimiento emocional',
    'frustración',
    'habilidades sociales',
    'herida emocional',
    'heridas del alma',
    'inestabilidad emocional',
    'insomnio',
    'irritabilidad',
    'lucha emocional',
    'maltrato emocional',
    'manejo de emociones',
    'meditación',
    'miedo',
    'optimismo',
    'orientación psicológica',
    'paciencia',
    'pareja',
    'paz mental',
    'perspectiva emocional',
    'preocupación',
    'problemas emocionales',
    'problemas familiares',
    'problemas laborales',
    'psicología',
    'psiquiatría',
    'psitacosis',
    'problemas de sueño',
    'problemas de la vida cotidiana',
    'psicoterapia',
    'recuperación emocional',
    'reducción del estrés',
    'rehabilitación emocional',
    'relación',
    'relajación',
    'resiliencia',
    'salud emocional',
    'salud mental',
    'sanación emocional',
    'satisfacción personal',
    'sexualidad',
    'solución de problemas',
    'superación personal',
    'terapia',
    'terapia cognitivo conductual',
    'terapia de pareja',
    'terapia de relajación',
    'terapia emocional',
    'terapia familiar',
    'terapia individual',
    'terapia ocupacional',
    'trabajo',
    'tranquilidad',
    'trauma',
    'trastorno',
    'trastorno alimentario',
    'trastorno de ansiedad',
    'trastorno de estrés postraumático',
    'trastorno de la personalidad',
    'transtorno emocional',
    'trastorno obsesivo compulsivo',
    'trastorno psicológico',
    'trastorno psiquiátrico',
    'trastornos alimentarios',
    'trastornos del estado de ánimo',
    'trastornos del sueño',
    'trastornos mentales',
    'tristeza',
    'valoración personal',
    'vínculo emocional',
    'vulnerabilidad emocional'
];