const disorders = [
    'abuso de drogas',
    'abuso de sustancias',
    'codependencia',
    'depresión',
    'desorden alimenticio',
    'desorden emocional',
    'duelo',
    'inestabilidad emocional',
    'insomnio',
    'irritabilidad',
    'maltrato emocional',
    'miedo',
    'psiquiatría',
    'psitacosis',
    'trastorno',
    'alimentario',
    'ansiedad',
    'estrés postraumático',
    'personalidad',
    'transtorno emocional',
    'obsesivo compulsivo',
    'psicológico',
    'psiquiátrico',
    'alimentarios',
    'estado de ánimo',
    'sueño',
    'mentales'
];

const problems = [
    'problemas',
    'aflicción',
    'ansia',
    'ansiedad',
    'cansancio',
    'desánimo',
    'desasosiego',
    'desesperación',
    'desgaste emocional',
    'desmotivación',
    'emociones negativas',
    'frustración',
    'herida emocional',
    'heridas del alma',
    'lucha emocional',
    'preocupación',
    'emocionales',
    'familiares',
    'laborales',
    'trauma',
    'tristeza',
    'vulnerabilidad emocional'
];

const selfHelp = [
    'acompañamiento',
    'amor propio',
    'autoayuda',
    'autoconocimiento',
    'autocuidado',
    'autoestima',
    'autoexigencia',
    'autoexploración',
    'bienestar',
    'bienestar emocional',
    'capacidad de adaptación',
    'comunicación efectiva',
    'confianza en uno mismo',
    'consejería',
    'consuelo',
    'cuidado personal',
    'desarrollo personal',
    'empatía',
    'energía emocional',
    'entendimiento interpersonal',
    'entrenamiento emocional',
    'equilibrio emocional',
    'esfuerzo personal',
    'familia',
    'fatiga',
    'felicidad',
    'fortalecimiento emocional',
    'habilidades sociales',
    'meditación',
    'optimismo',
    'orientación psicológica',
    'paciencia',
    'pareja',
    'paz mental',
    'perspectiva emocional',
    'problemas de la vida cotidiana',
    'psicología',
    'recuperación emocional',
    'reducción del estrés',
    'rehabilitación emocional',
    'relación',
    'relajación',
    'resiliencia',
    'salud emocional',
    'salud mental',
    'sanación emocional',
    'satisfacción personal',
    'sexualidad',
    'autoconocimiento',
    'autocuidado',
    'autoestima',
    'autoexigencia',
    'autoexploración'
];

const therapy = [
    'cognitivo conductual',
    'consejería',
    'psicológica',
];

const keywords = disorders.concat(problems, selfHelp, therapy);

module.exports = keywords;