name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/psintegra-chat:${{ github.sha }}

      - name: Push the Docker image to Docker Hub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/psintegra-chat:${{ github.sha }}
