name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up environment variables
        env:
          VITE_API: ${{ secrets.VITE_API }}
        run: |
          echo "VITE_API=${VITE_API}" >> .env

      - name: Build and tag the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/psintegra-chat:latest

      - name: Push the Docker image to Docker Hub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/psintegra-chat:latest
